name: Lambda Deployment Workflow

on:
  workflow_dispatch: # Allows this to be triggered by the test.yml workflow

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: lab # Ensures it pulls from your specific lab branch

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1 # Hardcoded here as per standard Lab requirements

      - name: Set Script Permissions
        run: chmod +x resources/deploy_lambda.sh

      - name: Run Deployment Script
        run: bash resources/deploy_lambda.sh